# The below option makes Vaelzan very sad. :(
"Creeper explosions destroy blocks" = false
"Creepie explosions destroy blocks" = false
"Creeper explosions spawn creepies" = true
"Creepers drop Creeper Spores after they die from an explosion" = true

